name: sample
description: Project created by Maksym Kovalchuk.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"
  
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  
  # Localizations - flutter gen-l10n
  flutter_localizations:
    sdk: flutter
  intl: any

  # System/Utilities
  path_provider: ^2.1.5
  meta: any 

  # BLoC
  flutter_bloc: ^9.1.1 
  bloc_concurrency: ^0.3.0

  # Stream
  rxdart: ^0.28.0

  # Networking
  http: ^1.5.0
  internet_connection_checker_plus: ^2.9.1

  # Persisting
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  flutter_secure_storage: ^9.2.4

  # Core
  get_it: ^9.0.5
  equatable: ^2.0.7
  flutter_local_notifications: ^19.5.0
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  go_router: ^16.3.0

  # Utils
  url_launcher: ^6.3.2
  html: ^0.15.6
  flutter_native_splash: ^2.4.7 
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.2
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  
  # UI
  cupertino_icons: ^1.0.8

  # Security
  uuid: ^4.5.2
  device_info_plus: ^12.2.0  
  package_info_plus: ^9.0.0

  # Logging
  logging: ^1.3.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^6.0.0

  # Utils
  flutter_flavorizr: ^2.4.1

  # Codegen
  hive_ce_generator: ^1.10.0
  build_runner: ^2.10.1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    prod:
      app:
        name: "sample"

      android:
        applicationId: "com.sample.app"
      ios:
        bundleId: "com.sample.app"

    dev:
      app:
        name: "sample-Dev"

      android:
        applicationId: "com.sample.app.dev"
      ios:
        bundleId: "com.sample.app.dev"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Nunito
    fonts:
      - asset: fonts/Nunito-Bold.ttf
      - asset: fonts/Nunito-SemiBold.ttf
      - asset: fonts/Nunito-Regular.ttf

  - family: RobotoFlex
    fonts:
      - asset: fonts/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  ios_content_mode: scaleAspectFit
  ios: true
  android: false
